// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/proto/gophkeeper.proto

package gophkeeperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_api_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_api_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT to send in the "authorization" metadata as "Bearer <token>".
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_api_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/gophkeeper.proto\x12\n" +
	"gophkeeper\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x88\x01\n" +
	"\vAuthService\x12=\n" +
	"\bRegister\x12\x17.gophkeeper.Credentials\x1a\x18.gophkeeper.AuthResponse\x12:\n" +
	"\x05Login\x12\x17.gophkeeper.Credentials\x1a\x18.gophkeeper.AuthResponseBBZ@github.com/dmitrymack/go-password-manager/api/proto;gophkeeperpbb\x06proto3"

var (
	file_api_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_api_proto_gophkeeper_proto_rawDescData []byte
)

func file_api_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_api_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_api_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gophkeeper_proto_rawDesc), len(file_api_proto_gophkeeper_proto_rawDesc)))
	})
	return file_api_proto_gophkeeper_proto_rawDescData
}

var file_api_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_gophkeeper_proto_goTypes = []any{
	(*Credentials)(nil),  // 0: gophkeeper.Credentials
	(*AuthResponse)(nil), // 1: gophkeeper.AuthResponse
}
var file_api_proto_gophkeeper_proto_depIdxs = []int32{
	0, // 0: gophkeeper.AuthService.Register:input_type -> gophkeeper.Credentials
	0, // 1: gophkeeper.AuthService.Login:input_type -> gophkeeper.Credentials
	1, // 2: gophkeeper.AuthService.Register:output_type -> gophkeeper.AuthResponse
	1, // 3: gophkeeper.AuthService.Login:output_type -> gophkeeper.AuthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_gophkeeper_proto_init() }
func file_api_proto_gophkeeper_proto_init() {
	if File_api_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gophkeeper_proto_rawDesc), len(file_api_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_api_proto_gophkeeper_proto_depIdxs,
		MessageInfos:      file_api_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_api_proto_gophkeeper_proto = out.File
	file_api_proto_gophkeeper_proto_goTypes = nil
	file_api_proto_gophkeeper_proto_depIdxs = nil
}
